Use wget tries / retry logic

diff --git a/recipes-core/entropy-tss/init b/recipes-core/entropy-tss/init
--- a/recipes-core/entropy-tss/init
+++ b/recipes-core/entropy-tss/init
@@ -20,15 +20,11 @@ METADATA_URL="http://metadata.google.internal/computeMetadata/v1/instance/attrib
 # For GCP, get chain endpoint from metadata
 get_config_from_metadata() {
     if [ -n "$CHAIN_ENDPOINT" ]; then
-        echo "[*] CHAIN_ENDPOINT is already set: $CHAIN_ENDPOINT"
+        echo "CHAIN_ENDPOINT is already set: $CHAIN_ENDPOINT"
     else
-        echo "[*] CHAIN_ENDPOINT not set, attempting to fetch from metadata..."
-
-        if ping -c 1 metadata.google.internal >/dev/null 2>&1; then
-            CHAIN_ENDPOINT=$(wget --header="Metadata-Flavor: Google" -qO - "${METADATA_URL}/${METADATA_KEY}")
-        else
-            echo "[!] Metadata server not reachable."
-        fi
+        echo "CHAIN_ENDPOINT not set, attempting to fetch from metadata..."
+        CHAIN_ENDPOINT=$(wget --header="Metadata-Flavor: Google" --tries=35 --waitretry=30 -qO - "${METADATA_URL}/${METADATA_KEY}") \
+           || echo "Failed to set chain endpoint"
     fi
 }
 
